django_root/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #url(r'^', include('dashboard.urls')),
    url(r'^', include('timetable.urls')),
 
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('allauth.urls')),

    url(r'^rooms/', include('rooms.urls')),
    url(r'^time/', include('timetable.urls')),
    url(r'^messages/', include('conmessages.urls')),
    #url(r'^main/', include('psyfako_core.urls')),
    
    # bonus
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^dash/', include('dashboard.urls')),
]

'''
    TODO enable favicon
    http://staticfiles.productiondjango.com/blog/failproof-favicons/
'''

rooms/urls.py
from django.conf.urls import url

from . import views

app_name = 'rooms'
urlpatterns = [
    url(r'^(?P<room_id>[0-9]+)/$', views.detail, name='detail'),
]

timetable/urls.py
from django.conf.urls import url
from datetime import datetime

from . import views

app_name = 'timetable'

urlpatterns = [
    url(r'^$', views.index, {'year': datetime.today().year, 'month': datetime.today().month, 'day': datetime.today().day}, name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', views.index, name='index'),
    url(r'^(?P<slot_id>[0-9]+)/$', views.detail, name='detail'),
]

timetable/models.py
from django.db import models

from psyfako_core.models import Member
from rooms.models import Room


class Slot(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=3, default='')
    start_time = models.DateTimeField('Start Time') 
    end_time = models.DateTimeField('End Time')
    
    def __str__(self):
        return self.name
                 
group_choices = ("Diskussion","Positionspapier")

class Workgroup(models.Model):
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, default = '')
    group_type_choices = (
        ('O', 'Offen'),    
        ('A', 'Austausch'),
        ('W', 'Arbeit'),
        ('P', 'Positionspapier'),
    )
    group_type = models.CharField(max_length=1, choices=group_type_choices)
    moderation = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="moderation")
    protocol = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, related_name="protocol")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True)
    
    def __str__(self):
        return self.title

timetable/views.py
from django.shortcuts import get_object_or_404, render
from datetime import datetime


from .models import Slot

def index(request, year, month, day):
    slot_list = Slot.objects.filter(start_time__year=str(year), start_time__month=str(month), start_time__day=str(day)).order_by('start_time')
    weekday = datetime(int(year), int(month), int(day)).weekday()
    if(weekday == 0):
        weekday = "Montag"
    elif(weekday == 1):
        weekday = "Dienstag"
    elif(weekday == 2):
        weekday = "Mittwoch"
    elif(weekday == 3):
        weekday = "Donnerstag"
    elif(weekday == 4):
        weekday = "Freitag"
    elif(weekday == 5):
        weekday = "Samstag"
    else:
        weekday = "Sonntag"
    
    day_before = int(day) - 1
    day_after= int(day) +1
    
    context = {
        'year': year,
        'month': month,
        'day': day,
        'day_before': day_before,
        'day_after': day_after,
        'weekday': weekday,
        'slot_list': slot_list,
    }
    return render(request, 'timetable/index.html', context)
    
def detail(request, slot_id):
    slot = get_object_or_404(Slot, pk=slot_id)
    return render(request, 'timetable/detail.html', {'slot': slot})

timetable/templates/timetable/detail.html
<h1>{{ slot.name }}</h1>
<ul>
{% for workgroup in slot.workgroup_set.all %}
    <li>{{ workgroup.title }}</li>
{% endfor %}
</ul>

timetable/templates/timetable/index.html
{% extends 'globalbase.html' %}
{% load static %} 

{% block title %}
PsyFaKo-App | Zeitplan
{% endblock title %}

{% block headertitle %}
Zeitplan
{% endblock headertitle %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'timetable/style.css' %}" />

<div class="date-nav"><a href="{% url 'timetable:index' year=year month=month day=day_before %}"><div class="arrow-left"></div></a><div class="date"><h1>{{weekday}}, {{day}}.{{month}}.</h1></div><a href="{% url 'timetable:index' year=year month=month day=day_after %}"><div class="arrow-right"></div></a></div>

{% if slot_list %}
    <div class = "timeslots">
    {% for slot in slot_list %}
        
        <div class = "slot">
                <header>
				<div class="program-circle">{{ slot.short_name }}</div>
				<h3><a href="{% url 'timetable:detail' slot.id %}">{{ slot.name }}</a></h3>
				<div class="program-time"> {{slot.start_time|time:"H:i"}}h - {{slot.end_time|time:"H:i"}}h </div>
        	     </header>
                {%if slot.workgroup_set.all%}
                {% for workgroup in slot.workgroup_set.all %}
                {% if workgroup.group_type == "O" %}
                <div class = "workgroup open-group">
                {% elif workgroup.group_type == "A" %}
                <div class = "workgroup exchange-group">
                {% elif workgroup.group_type == "W" %}
                <div class = "workgroup working-group">
                {% elif workgroup.group_type == "P" %}
                <div class = "workgroup position-group">
                {% endif %}
                <h5>{{workgroup.title}}</h5>
                <b>Moderation:</b> {{workgroup.moderation}}<br> 
                <b>Protokoll:</b> {{workgroup.protocol}} <br>
                <b>Raum:</b> <a href="{% url 'rooms:detail' workgroup.room.id %}">{{workgroup.room.name}} ({{workgroup.room.building.short_name}}/{{workgroup.room.floor}}.{{workgroup.room.nr}})</a>
                <a href="http://pad.psyfako.org:7733/p/PsyFaKo-{{workgroup.id}}-{{slot.short_name}}" target="_blank"><div class="protocol-icon"></div></a>                
                </div>
                {% endfor %}
                {% else %}
                <p>Noch keine Arbeitskreise eingetragen.</p>
                {% endif %}
            </div>        
    {% endfor %}
    </div>
{% else %}
    <p>Für diesen Tag wurden noch keine Zeitslots festgelegt.</p>
{% endif %}
{% endblock content %}